do_you_want_to_continue=続行しますか? ({{y/n}}):

catfood_warning=<@w>警告: ネコカンを編集すると BAN される可能性があります。自己責任で使用してください。</>\n{{do_you_want_to_continue}}
legend_ticket_warning=<@w>警告: レジェンドチケットを編集すると BAN される可能性があります。自己責任で使用してください。</>\n{{do_you_want_to_continue}}
rare_ticket_warning=
><@w>警告: レアチケットを編集すると BAN される可能性があります。自己責任で使用してください。</>
>BAN リスクを下げてレアチケットを入手するには、レアチケット交換機能を使用できます。
platinum_ticket_warning=
><@w>警告: プラチナチケットを編集すると BAN される可能性があります。自己責任で使用してください。</>
>BAN リスクを下げてプラチナチケットを入手するには、プラチナのかけら機能を使用できます。

select_an_option_to_continue={feature_name} の編集を続けるにはオプションを選択してください:

continue_editing={feature_name} の編集を続行
go_to_safe_feature=より安全な {safer_feature_name} 機能へ移動
cancel_editing={feature_name} の編集をキャンセル

rare_ticket_trade_enter=<@q>追加</> したいレアチケット数を入力してください (最大値: <@q>{max}</>) (現在数: <@q>{current}</>):
rare_ticket_trade_storage_full=<@e>エラー: にゃんこ貯蔵庫に十分な空きがありません。1枠空けてください!</>
rare_ticket_successfully_traded=
><@su>{rare_ticket_count} 枚のレアチケットを付与しました。</>
>チケットを受け取るには、にゃんこ貯蔵庫に入り、<@q>すべて使う</> ボタンを押してから <@q>チケットに交換</> ボタンを押してください。

rare_tickets_l=レアチケット
rare_ticket_trade_l=レアチケット交換

rare_ticket_trade_maxed=<@e>エラー: すでにレアチケットの最大所持数に達しています!\nこの機能を実行する前にいくつか使用してください!</>

platinum_tickets_l=プラチナチケット
platinum_shards_l=プラチナのかけら
