total_selected_cats=現在 <@t>{total}</> 体のキャラが選択されています
selected_cat=<@t>{name}</> (<@t>{id}</>) が選択されています

cat=<@t>{name}</> (<@t>{id}</>)
special_skill=<@t>{name}</> (<@t>{id}</>)
item=<@t>{name}</> (<@t>{id}</>)
cat_quantity=追加したい {{cat}} の数を入力してください (既定 <@t>1</t>):
skill_quantity=追加したい <@t>{name}</> の数を入力してください (既定 <@t>1</t>):
unrecognised_storage_item=<@e>認識できない貯蔵庫アイテムです。アイテムカテゴリ: <@s>{item_type}</>。アイテム ID: <@s>{id}</> </>
current_storage_items=現在の貯蔵庫アイテム:
storage_is_empty=貯蔵庫は空です
available_storage=利用可能な貯蔵庫の空き: <@t>{slots}</>
display_storage=貯蔵庫を表示
clear_storage=貯蔵庫を空にする
add_cats=キャラを追加
add_special_skills=青玉を追加
remove_items=キャラ / 青玉を削除
too_many_cats_selected=<@e>選択したキャラが多すぎます。最大は <@s>{max}</>、現在は <@s>{current}</> です</>
too_many_skills_selected=<@e>選択した青玉が多すぎます。最大は <@s>{max}</>、現在は <@s>{current}</> です</>
need_x_more_space=<@e>貯蔵庫の空きが足りません。あと <@s>{needs}</> 枠必要です</>
added_cats=追加したキャラ:
added_special_skills=追加した青玉:
select_special_skills=青玉を選択
removed_items=削除したアイテム:
cat_storage=にゃんこ貯蔵庫
storage_success=<@su>にゃんこ貯蔵庫を編集しました</>

select_gv=
>絞り込むゲームバージョンを入力してください。例:
>- バージョン <@t>11.5.0</> のキャラだけ取得: <@t>11.5.0</>,
>- バージョン <@t>12.4.0</> と <@t>13.0.0</> のキャラだけ取得: <@t>12.4.0 13.0.0</>
>- バージョン <@t>12.4.0</> から <@t>13.0.0</> までのキャラをすべて取得: <@t>12.4.0-13.0.0</>
>パワーアップメニューに表示されないキャラは、ゲームバージョンが <@t>-1</> に設定されているため、ここでは選択できません。
>入力:

possible_gvs=指定可能なゲームバージョン:

no_valid_gvs_entered=<@w>有効なゲームバージョンが入力されていません</>

select_cats_rarity=レアリティでキャラを選択
select_cats_name=名前でキャラを選択
select_cats_obtainable=入手可能なキャラをすべて選択
select_cats_not_obtainable=入手不可のキャラをすべて選択
select_cats_gatya_banner=ガチャバナーでキャラを選択
select_cats_game_version=ゲームバージョンでキャラを選択
select_cats_all=すべてのキャラを選択
select_cats=キャラを選択:
and_mode_q=現在の選択を絞り込みますか (<@t>1</>)、選択に追加しますか (<@t>2</>)、置き換えますか (<@t>3</>)?:
select_rarity=キャラのレアリティを選択:
enter_name=キャラ名を入力してください:
select_name=キャラ名を選択:
select_gatya_banner=ガチャバナー ID を入力してください {{range_input}}
cats=キャラ
edit_cats=キャラを編集
enter_cat_ids=キャラ ID はここで確認できます: <@t>https://battlecats.miraheze.org/wiki/Cat_Release_Order</>\nキャラ ID を入力してください {{range_input}}
select_cats_id=ID でキャラを選択
no_cats_found_name=<@w><@s>{name}</> という名前のキャラは見つかりませんでした</>

select_cats_again=追加のキャラを選択
unlock_cats=キャラを解放|キャラを入手
remove_cats=キャラを削除
upgrade_cats=キャラを強化
true_form_cats=キャラを第3形態にする
remove_true_form_cats=キャラの第3形態を削除
upgrade_talents_cats=キャラの本能を強化
remove_talents_cats=キャラの本能を削除
unlock_cat_guide=にゃんこ図鑑を登録済みにする
remove_cat_guide=にゃんこ図鑑を未登録にする
finish_edit_cats=キャラ編集を終了
select_edit_cats_option=キャラを編集するオプションを選択してください:

upgrade_success=<@su>キャラを強化しました</>
upgrade_cats_select_mod=キャラを強化するオプションを選択してください:
upgrade_individual=選択した各キャラの強化値を入力
selected_cat_upgrades={{selected_cat}}: <@t>{base_level}<@s>+</>{plus_level}</>
selected_cat_upgraded=<@t>{name}</> (<@t>{id}</>) を <@t>{base_level}<@s>+</>{plus_level}</> に強化しました
upgrade_all=選択したすべてのキャラに適用する強化値を入力
upgrade_input=
>強化レベルを入力してください。例:
><@t>10<@s>+</>20</> = 基本レベル 10、プラス値 20
><@t>10<@s>+</></> = 基本レベル 10、現在のプラス値を維持
><@t><@s>+</>20</> = 現在の基本レベルを維持、プラス値 20
><@t>10</> = 基本レベル 10、プラス値 0
><@t>5<@q>-</>10<@s>+</>20<@q>-</>30</> = 基本レベルを 5 から 10 の間でランダム、プラス値を 20 から 30 の間でランダム
><@t>5<@q>-</>10<@s>+</></> = 基本レベルを 5 から 10 の間でランダム、現在のプラス値を維持
><@t><@s>+</>20<@q>-</>30</> = 現在の基本レベルを維持、プラス値を 20 から 30 の間でランダム
><@t>{{max}}<@s>+</>{{max}}</> = 基本レベル最大、プラス値最大
><@t>{{quit_key}}</> = 終了
>入力:

max_upgrade=強化レベル上限: <@t>{max_base}<@s>+</>{max_plus}</>

invalid_upgrade_base=<@e>基本レベルが無効です: <@s>{base}</>
invalid_upgrade_base_random=<@e>基本レベル範囲が無効です: <@s>{min}</>-<@s>{max}</>
invalid_upgrade_plus=<@e>プラス値が無効です: <@s>{plus}</>
invalid_upgrade_plus_random=<@e>プラス値範囲が無効です: <@s>{min}</>-<@s>{max}</>

remove_true_form_success=<@su>第3形態を削除しました</>
true_form_success=<@su>キャラを第3形態にしました</>

remove_success=<@su>キャラを削除しました</>
unlock_success=<@su>キャラを解放しました</>

unlock_cat_guide_success=<@su>にゃんこ図鑑項目を登録済みにしました</>
remove_cat_guide_success=<@su>にゃんこ図鑑項目を未登録にしました</>

select_cats_current=現在解放済みのキャラを選択
select_cats_not_unlocked=まだ解放されていないキャラを選択

talents_version_warning=
><@w>警告: エディタのゲームデータが、このセーブファイルのゲームバージョンと一致していません。本能が想定どおり動作しない可能性があります。
>セーブバージョン: <@s>{save_version}</>
>ゲームデータバージョン: <@s>{data_version}</>
>ゲームデータが古い場合は、数日以内に更新されるはずです。</>

talents_success=<@su>キャラの本能を強化しました</>
talents_remove_success=<@su>キャラの本能を削除しました</>
talents_individual=選択した各キャラの本能を編集
talents_all=選択したすべてのキャラの本能を最大化
upgrade_talents_select_mod=キャラの本能を編集するオプションを選択してください:
no_talent_data=<@w>このキャラの本能データはありません</>
talents=本能
upgrade_talent_cats=キャラの本能を強化
force_true_form_cats=キャラの第3形態を強制設定
force_true_form_cats_warning=
><@w>警告: そのキャラに第3形態があると分かっている場合のみ使用してください。そうでない場合、壊れた第3形態になります。
>主な用途は、エディタのゲームデータが古く、新しい第3形態がまだ追加されていない場合です。</>

filter_current_q=現在解放済みのキャラだけから選択しますか (<@t>1</>)、それとも全キャラから選択しますか (<@t>2</>)?:
select_cats_currently_option=現在解放済みのキャラから選択 (例: 特定レアリティのキャラを選ぶとき、現在解放済みのそのレアリティのキャラだけを選択)
select_cats_all_option=すべてのキャラから選択

unlock_remove_cats=キャラを解放 / キャラを削除
true_form_remove_form_cats=第3形態にする / 第3形態を削除
upgrade_talents_remove_talents_cats=本能を強化 / 本能を削除
unlock_remove_cat_guide=にゃんこ図鑑項目を登録 / 未登録

unlock_remove_q=キャラを <@t>解放</> しますか、それとも <@t>削除</> しますか?:
true_form_remove_form_q=キャラを <@t>第3形態</> にしますか、それとも <@t>第3形態を削除</> しますか?:
upgrade_talents_remove_talents_q=キャラの本能を <@t>強化</> しますか、それとも <@t>削除</> しますか?:
unlock_cat_guide_remove_guide_q=にゃんこ図鑑項目を <@t>登録</> しますか、それとも <@t>未登録</> にしますか?:

fourth_form_remove_form_cats=第4形態を削除
force_fourth_form_cats=キャラの第4形態を強制設定
fourth_form_success=<@su>キャラを第4形態にしました</>
remove_fourth_form_success=<@su>第4形態を削除しました</>
fourth_form_cats=キャラを第4形態にする
remove_fourth_form_cats=キャラの第4形態を削除
fourth_form_remove_form_q=キャラを <@t>第4形態</> にしますか、それとも <@t>第4形態を削除</> しますか?:
force_fourth_form_cats_warning=
><@w>警告: そのキャラに第4形態があると分かっている場合のみ使用してください。そうでない場合、壊れた第4形態になります。
>主な用途は、エディタのゲームデータが古く、新しい形態がまだ追加されていない場合です。</>

gatya_info_progress=ガチャ情報をダウンロードしています (<@t>{current}</>/<@t>{total}</>)
unknown_banner=不明なバナー
banner_txt={name} (<@s>{int}</>)
filter_down_q_gatya=一覧から重複バナーと不明なバナーを削除しますか? ({{y/n}}):

select_cats_non_gatya=ガチャ以外のキャラを選択
finished_cats_selection=キャラの選択を完了しましたか? ({{y/n}}):

downloading_cat_names=<@su><@s>{url}</> からキャラ名をダウンロードしています</>
