total_selected_enemies=現在 <@t>{total}</> 体の敵が選択されています
unlock_enemy_guide_success=<@su>敵図鑑の項目を解放しました</>
remove_enemy_guide_success=<@su>敵図鑑の項目を削除しました</>
selected_enemy=<@t>{name}</> (<@t>{id}</>) が選択されています
select_enemies_valid=敵図鑑に登録済みの敵をすべて選択
select_enemies_invalid=敵図鑑に未登録の敵をすべて選択
select_enemies_all=すべての敵を選択
select_enemies_id=ID で敵を選択
select_enemies_name=名前で敵を選択
select_enemies=敵を選択:
enter_enemy_ids=敵 ID はここで確認できます: <@t>https://battlecats.miraheze.org/wiki/Enemy_Release_Order</>\n敵 ID を入力してください {{range_input}}:
enter_enemy_name=敵の名前を入力してください:
enemy_not_found_name=<@w><@s>{name}</> という名前の敵は見つかりませんでした</>
unlock_enemy_guide=敵図鑑の項目を解放
remove_enemy_guide=敵図鑑の項目を削除
enemy_guide=敵図鑑
edit_enemy_guide=敵図鑑項目を編集するオプションを入力してください:
