fix_gamatoto_crash=ガマトトでゲームがクラッシュする問題を修正
fix_time_errors=時間関連の問題を修正

fix_ototo_crash=オトートでゲームがクラッシュする問題を修正

fix_gamatoto_crash_success=<@su>ガマトトでゲームがクラッシュする問題を修正しました</>
fix_time_errors_success=<@su>時間関連の問題を修正しました <@w>(これが動作するには、両方の端末で端末時刻が正しい必要があります)</></>
fix_ototo_crash_success=<@su>オトートでゲームがクラッシュする問題を修正しました</>

fixes=修正

unlock_equip_menu=編成メニューを解放
equip_menu_unlocked=<@su>編成メニューを解放しました</>
