enter_raw_gamatoto_xp=ガマトトの生 XP を入力
enter_gamatoto_level=ガマトトのレベルを入力
edit_gamatoto_level_q=ガマトトのレベルを編集するオプションを入力してください:
gamatoto_xp=ガマトト XP
gamatoto_level=ガマトト レベル
gamatoto_level_success=<@su>ガマトトのレベルを <@s>{level}</> に設定しました (XP: <@s>{xp}</>)</>
gamatoto_level_current=<@t>現在のガマトトレベルは <@q>{level}</> です (XP: <@q>{xp}</>)</>
gamatoto_xp_level=ガマトト XP / レベル

current_gamatoto_helpers=現在の隊員:
gamatoto_helper=隊員: <@t>{name}</> (レアリティ: <@t>{rarity_name}</>)

new_gamatoto_helpers=新しい隊員:
gamatoto_helpers=ガマトト隊員

ototo_cat_cannon=オトート開発隊

current_cannon_stats=現在の主砲ステータス:

cannon_part=<@t><@q>{name}</>{buffer}(レベル <@s>{level}</>)</>
development={buffer}(開発状況: <@q>{development}</>)
cannon_stats={parts}

foundation=土台
style=装飾
effect=効果
improved_foundation=強化土台
improved_style=強化装飾

unknown_stage=不明な段階 (<@s>{stage}</>)

selected_cannon=<@t>選択中の主砲: <@q>{name}</></>
selected_cannon_stage=<@t>主砲: <@q>{name}</> 現在の段階: <@q>{stage}</></>

cannon_edit_type=各主砲を個別に編集しますか、それとも選択したすべての主砲へ一括適用しますか?:

cannon_dev_level_q=主砲の開発状況を編集しますか、それとも主砲レベルを編集しますか?:
development_o=開発状況
level_o=レベル

select_development=開発段階を選択:
select_cannon=主砲を選択
cannon_level=主砲レベル

cannon_success=<@su>主砲を編集しました</>

cat_shrine=ネコ神社を編集
shrine_level=神社レベルを編集
shrine_xp=神社 XP
current_shrine_xp_level=<@t>現在の XP: <@q>{xp}</> (レベル: <@q>{level}</>)</>
cat_shrine_choice_dialog=何をしますか?:
shrine_level_dialog=ネコ神社レベルを入力してください (最大: <@q>{max_level}</>):
shrine_xp_dialog=ネコ神社 XP を入力してください (最大: <@q>{max_xp}</>):
cat_shrine_edited=<@su>ネコ神社を編集しました</>
make_catshrine_appear=ゲーム内にネコ神社を表示
make_catshrine_disappear=ゲーム内のネコ神社を非表示
