event_tickets=イベントチケット / 福引チケット
downloading_gatya_data=ガチャイベントデータをダウンロードしています...
download_gatya_data_success=<@su>ガチャイベントデータをダウンロードしました</>
download_gatya_data_fail=<@e>ガチャイベントデータのダウンロードに失敗しました。もう一度試してください</>
save_gatya_error=<@e>{error} によりガチャデータを保存できませんでした</>
gatya_by_id_q=ガチャバナーを <@t>ID</> と <@t>名前</> のどちらで選択しますか?:
by_id=ID で選択
by_name=名前で選択
