gold_pass_dialog=使用したい <@t>会員番号</> を入力してください (<@q>空欄</> で <@q>ランダム</> ID、<@q>-1</> でゴールド会員を <@q>削除</>):
gold_pass=ゴールド会員
gold_pass_remove_success=<@su>ゴールド会員を削除しました</>
gold_pass_get_success=<@su>ゴールド会員を取得しました (id: <@t>{id}</>)</>。<@w>注意: 実際には所持していないとゲーム側が判断した場合、ゴールド会員が削除されることがあります。これは修正できないため、この件のバグ報告はしないでください。</>
officer_pass_fixed=<@su>にゃんこクラブのクラッシュを修正しました</>
fix_officer_pass_crash=にゃんこクラブのクラッシュを修正
