# Note that not all items are here

catamins=ネコビタン
catfruit=マタタビ
base_materials=城素材
inquiry_code=問い合わせコード
rare_gatya_seed=レアガチャシード
normal_gatya_seed=にゃんこガチャシード
event_gatya_seed=イベントガチャシード
unlocked_slots=出陣スロット
password_refresh_token=パスワード更新トークン
challenge_score=チャレンジバトルスコア
dojo_score=初心の間スコア
items=アイテム
user_rank_rewards=ユーザーランク報酬を受け取る (報酬自体は付与されません)

catfood=ネコカン
xp=XP
normal_tickets=にゃんこチケット
rare_tickets=レアチケット
platinum_tickets=プラチナチケット
legend_tickets=レジェンドチケット
100_million_tickets=1億ダウンロード記念チケット
100_million_warn=<@w>注意: 1億ダウンロードイベントが現在有効な場合のみ、このチケットを表示/使用できます</>
platinum_shards=プラチナのかけら
np=NP
leadership=リーダーシップ
catseyes=キャッツアイ
battle_items=バトルアイテム
duration=<@t>{days}</t> 日, <@t>{hours}</t> 時間, <@t>{minutes}</> 分, <@t>{seconds}</> 秒
endless_item_item=<@s>{item}</> : <@s>{int}</>
endless_items_success=<@su>アイテム使い放題を編集しました</>
invalid_minute_count=<@e>分数が無効です</>
enter_duration_minutes=アイテム使い放題の継続時間を分で入力してください (<@t>infinity</> と入力すると永久に継続します):
infinity_duration=<@t>infinity</>
infinity=無限
enter_duration_minutes_item=無期限 <@t>{item}</> の継続時間を分で入力してください (<@t>infinity</> と入力すると永久に継続します):
battle_items_endless=アイテム使い放題(無期限化)
talent_orbs=本能玉
scheme_items=外部報酬
labyrinth_medals=グランドアビス勲章
restart_pack=リスタートパック
engineers=助手
gamototo=ガマトト / オトート
special_skills=施設レベル
treasure_chests=本能玉宝箱
unknown_treasure_chest_name=不明な宝箱 ({id})

rare_ticket_trade=レアチケット交換
rare_ticket_trade_feature_name=レアチケット交換 (BAN されにくいレアチケットを入手)

other=その他
gatya=ガチャ
levels=レベル / ストーリー / お宝
cats_special_skills=キャラ / 施設レベル

gatya_item_unknown_name=不明なアイテム
unknown_catamin_name=不明なネコビタン <@t>{id}</>
unknown_catseye_name=不明なキャッツアイ <@t>{id}</>
unknown_catfruit_name=不明なマタタビ <@t>{id}</>
unknown_labyrinth_medal_name=グランドアビス勲章 <@t>{id}</>

reset_golden_cat_cpus_success=<@su>金ニャンピューターの使用回数をリセットしました</>
reset_golden_cat_cpus=ニャンピューター使用回数をリセット
edit_endless_q=各アイテム使い放題(無期限化)を <@t>個別</> に編集しますか、それとも <@t>一括</> で編集しますか?:
