tutorial_already_cleared=<@w>チュートリアルはすでにクリア済みです</>
tutorial_cleared=<@su>チュートリアルをクリアしました</>
clear_tutorial=チュートリアルをクリア

clear_stages=ステージをクリア
unclear_stages=ステージを未クリアに戻す
clear_unclear_q=ステージを <@t>クリア</> しますか、それとも <@t>未クリアに戻す</> しますか?:

add_enigma_stages=地図ステージを追加
clear_enigma_stages=地図ステージをクリア
current_enigma_stages=現在の地図ステージ:
enigma_stage=地図ステージ <@q>{name}</> (id: <@q>{id}</>) 
unknown_enigma_name=不明な地図ステージ名 (id: <@q>{id}</>)
enigma_select=追加する地図ステージを選択
enigma_success=<@su>地図ステージを追加しました</>
wipe_enigma=現在の地図ステージを消去しますか? ({{y/n}}):
aku_realm_unlocked=<@su>魔界編を解放しました</>
unlock_aku_realm=魔界編を解放

select_story_chapters=ストーリーを選択
chapter_progress_txt=(例 <@q>0</> = クリア済みステージなし, <@q>1</> = 最初のステージをクリア済み, <@q>2</> = 1番目と2番目のステージをクリア済み, ... <@q>{max}</> = 全ステージクリア済み)
edit_chapter_progress_all=各章に設定する進行度を入力してください {{chapter_progress_txt}}:
edit_chapter_progress=<@t>{chapter_name}</> に設定する進行度を入力してください {{chapter_progress_txt}}:
edit_stage_clear_count=ステージのクリア回数を入力してください:
story_cleared=<@su>ストーリーをクリアしました</>
individual_chapters=個別の章
all_chapters=すべての章
individual_chapters_dialog=各章のクリア進行度を <@t>個別</> に編集しますか? それとも <@t>すべて</> の章を同じ進行度にしますか?:
individual_clear_counts=個別のクリア回数
all_clear_counts=すべて同じクリア回数
individual_clear_counts_dialog=各ステージのクリア回数を <@t>個別</> に編集しますか? それとも <@t>すべて</> のステージを同じクリア回数にしますか?:
clear_story=メインストーリー|ストーリーをクリア

map_name_star={name} {star} 冠

clear=クリア
unclear=未クリアに戻す

outbreaks=ゾンビステージ

clear_unclear_outbreaks=ゾンビステージを <@t>クリア</> しますか、それとも <@t>未クリアに戻す</> しますか?:
clear_outbreaks_success=<@su>ゾンビステージをクリアしました</>
unclear_outbreaks_success=<@su>ゾンビステージを未クリアに戻しました</>
no_valid_outbreaks=<@e>エラー: 有効なゾンビステージが見つかりません</>

aku_chapters=魔界編の章
aku_clear_success=<@su>魔界編をクリアしました</>
aku_current_stage=魔界編ステージ <@q>{name}</> (id: <@q>{id}</>)

itf_timed_scores=未来編タイムスコア
itf_timed_scores_dialog=タイムスコアを <@t>章全体で一括</> 編集しますか、それとも <@t>個別ステージ</> ごとに編集しますか?
itf_timed_scores_edited=<@su>未来編のタイムスコアを編集しました</>
itf_timed_score_dialog=タイムスコアを入力してください:
current_stage={chapter_name} <@t>{stage_name}</>
itf_timed_scores_individual_dialog=選択した各ステージのタイムスコアを <@t>個別</> に編集しますか? それとも <@t>選択したすべて</> のステージを同じタイムスコアにしますか?:

filibuster_stage_reclearing_allowed=<@su>フィリバスターステージを再挑戦可能にしました。</>
filibuster_reclearing=フィリバスターステージを再挑戦可能にする

all_selected_stages=選択したすべてのステージ

unknown_map_name=不明なマップ名 (id: <@q>{id}</>)
map_name={name} <@s>(id: <@q>{id}</>)</>
edit_map_chapters=章を選択

clear_whole_chapters=章全体をクリア
unclear_whole_chapters=章全体を未クリアに戻す

clear_specific_stages=特定ステージをクリア
unclear_specific_stages=特定ステージを未クリアに戻す

select_clear_type=<@t>章全体をクリア</> しますか、それとも <@t>特定ステージをクリア</> しますか?:
select_unclear_type=<@t>章全体を未クリアに戻す</> しますか、それとも <@t>特定ステージを未クリアに戻す</> しますか?:

custom_star_count_per_chapter_yn=各章にカスタム星/冠数を設定しますか? ({{y/n}}):
modify_clear_amounts=選択した各ステージのクリア回数を <@t>1</> に設定します。これを変更しますか? ({{y/n}}):
clear_amount_chapter=選択した各章に異なるクリア回数を設定
clear_amount_all=選択したすべての章に同じクリア回数を設定
clear_amount_stages=選択した各ステージに異なるクリア回数を設定
select_clear_amount_type=使用するクリア回数設定モードを入力してください:
clear_amount_enter=クリア回数を入力してください:
custom_star_count_per_chapter=星/冠数を入力してください (最大 <@q>{max}</>):

custom_star_count_per_chapter_unclear=
>削除する星/冠を入力してください:
><@s><@t>1</> = マップ全体から未クリアに戻す</>
><@s><@t>2</> = 2冠/星、3冠/星、4冠/星マップから未クリアに戻す</>
><@s><@t>3</> = 3冠/星、4冠/星マップから未クリアに戻す</>
><@s><@t>4</> = 4冠/星マップから未クリアに戻す</>
>(最大 <@q>{max}</>):

current_sol_chapter=章 <@t>{name}</> (id: <@q>{id}</>)
current_sol_star=星/冠: <@q>{star}</>
current_sol_stage=ステージ <@q>{name}</> (id: <@q>{id}</>)
map_chapters_edited=<@su>章を編集しました</>
sol=レジェンドストーリー
event=通常イベントステージ
collab=コラボイベントステージ
select_map=マップを選択
select_map_dialog=
>編集するマップを選択してください
>数値範囲 (例 <@q>1-5</>)、個別の数値 (例 <@q>1 3 5</>)、またはその組み合わせ (例 <@q>1-3 5</>) を入力できます
>マップ名または名前の一部 (例 <@t>{example}</>) を入力して検索/選択することもできます
><@q>all</> と入力するとすべての章を選択できます
>入力:
no_map_found=<@e><@s>{name}</> という名前のマップは見つかりませんでした</>
finished_selecting_maps=マップの選択を完了しましたか? ({{y/n}}):
current_maps=現在のマップ:

select_stage=ステージを選択

gauntlets=強襲ステージ
collab_gauntlets=コラボ強襲ステージ
uncanny=真レジェンドストーリー
catamin_stages=ネコビタンステージ
behemoth_culling=超獣討伐ステージ
legend_quest=レジェンドクエスト
towers=にゃんこ塔
zero_legends=ゼロレジェンド

unclear_other_stages=章内の現在の進行状況を上書きしますか? ({{y/n}}) <@t>n</> = 選択したステージのクリア回数だけを変更, <@t>y</> = 以前クリア済みだった章内の後続ステージを未クリアに戻す:

select_stage_progress=ここまで含めてクリアするステージを入力してください:

zero_legends_warning=<@w>警告: 使用中のゲームバージョンにゼロレジェンドマップがない場合、クリア済みに編集するとゲームがクラッシュします!</>

stages_select=数値を入力してください {{range_input}}

change_clear_amount_catamin=章のクリア回数を変更
clear_unclear_stage_catamin=ネコビタンステージをクリア / 未クリアに戻す
catamin_stage_clear_q=<@t>ネコビタン章のクリア回数を変更</> しますか、それとも単に <@t>ステージをクリア/未クリアに戻す</> しますか?:

select_map_from_names=マップを選択

enter_clear_amount_catamin_map=章 <@t>{name}</> (ID: <@t>{id}</t>) に設定するクリア回数を入力してください (<@t>0</> = この章を未クリア, <@t>3</> 以上 = 章が消えます):
enter_clear_amount_catamin=選択した章に設定するクリア回数を入力してください (<@t>0</> = 章を未クリア, <@t>3</> 以上 = 章が消えます):

catamin_stage_success=<@su>ネコビタンステージを編集しました</>

catamin_clear_amounts_q=各章のクリア回数を <@t>個別</> に編集しますか、それとも <@t>一括</> で編集しますか?:

dojo_catclaw_championships=にゃんこ道検定をクリア

finished=完了
edit_chapters_q=何を編集しますか?:

clear_whole_chapter=章全体をクリア
clear_to_specific_stage=特定ステージまでクリア
clear_whole_q=<@t>章全体を一括でクリア</> しますか、それとも <@t>章内の特定ステージまでクリア</> しますか?:

clear_all=すべての章をクリア
handle_individually=各章を個別に編集

clear_chapters_q=<@t>選択したすべての章をクリア</> しますか、それとも <@t>各章の進行度を個別に編集</> しますか?:
max_stars=最大冠数を入力してください (最大: <@t>{max}</>):

edit_map_all=すべての章に同じクリア回数
edit_chapters_q_all=<@t>選択したすべての章に同じクリア回数</> を設定しますか、それとも <@t>各章のクリア回数</> を個別に編集しますか?

edit_whole_chapter=章全体に同じクリア回数を設定
edit_specific_stages=特定ステージのクリア回数を編集
edit_chapter_q=<@t>章内のすべてのステージに同じクリア回数を設定</> しますか、それとも <@t>特定ステージのクリア回数を編集</> しますか?:

each_stage_individually=選択した各ステージに異なるクリア回数を設定
stage_all_at_once=選択したすべてのステージに同じクリア回数を設定
set_clear_count_stage_q=<@t>選択した各ステージに異なるクリア回数を設定</> しますか、それとも <@t>選択したすべてのステージに同じクリア回数を設定</> しますか?:

unknown_stage_name=不明なステージ名 (index: <@t>{index}</>)
current_stage_map=<@t>{name} <@s>(index: <@q>{index}</>)</></>

edit_progress_clear=マップ進行度を編集
edit_progress_unclear=マップ進行度を編集 (未クリア化対応)
edit_clear_counts=ステージクリア回数を編集

keep_selecting=選択を続ける
remove_selection=選択を解除
finish_selection=選択を終了
map_selection_q=何をしますか?:
