medals=にゃんこメダル
add_medals=メダルを追加
remove_medals=メダルを削除
medal_add_remove_dialog=<@t>メダルを追加</> しますか、それとも <@t>メダルを削除</> しますか?:
medal_string={medal_name}: <@q>{medal_req}</>
select_medals=メダルを選択:
medals_added=<@su>にゃんこメダルを追加しました</>
medals_removed=<@su>にゃんこメダルを削除しました</>
