missions=ミッション
complete_reward=ミッションをクリア済みにして報酬は未受け取りにする
complete_claim=ミッションをクリア済みにして報酬受け取り済みにする
uncomplete=ミッションを未クリアにする
select_mission_claim=<@t>ミッションをクリア済みにして報酬は未受け取り</>、<@t>ミッションをクリア済みにして報酬受け取り済み <@q>(実際に報酬は付与されません)</></>、可能なら <@t>ミッションを未クリアにする</> のどれを行いますか?
select_missions=編集するミッションを選択:
missions_edited=<@su>ミッションを編集しました</>
