playtime_str=<@t>{hours}</> 時間, <@t>{minutes}</> 分, <@t>{seconds}</> 秒 (<@t>{frames}</> フレーム)
playtime_current=現在のプレイ時間: {{playtime_str}}
playtime_edited=プレイ時間を {{playtime_str}} に編集しました
playtime_hours_prompt=設定するプレイ時間の <@t>時間</> を入力してください:
playtime_minutes_prompt=設定するプレイ時間の <@t>分</> を入力してください:
playtime_seconds_prompt=設定するプレイ時間の <@t>秒</> を入力してください:
playtime=プレイ時間
