scheme_items_edit_success=<@su>外部報酬を編集しました</>
scheme_items_select_gain=入手する外部報酬を選択
scheme_items_select_remove=削除する外部報酬を選択
gain_remove_scheme_items=外部報酬を <@t>入手</> しますか、それとも <@t>削除</> しますか?:
gain_scheme_items=外部報酬を入手
remove_scheme_items=外部報酬を削除
