special_skills_dialog=強化する施設レベルを選択
upgrade_individual_skill=選択した各施設レベルの強化値を入力
upgrade_all_skills=選択したすべての施設レベルに適用する強化値を入力

upgrade_skills_select_mod=施設レベルを強化するオプションを選択してください:

selected_skill=<@t>{name}</> が選択されています
selected_skill_upgrades={{selected_skill}}: <@t>{base_level}<@s>+</>{plus_level}</>
selected_skill_upgraded=<@t>{name}</> を <@t>{base_level}<@s>+</>{plus_level} に強化しました
skills_edited=<@su>施設レベルを編集しました</>
