total_current_orbs=現在の本能玉合計: <@q>{total_orbs}</>
total_current_orb_types=現在の本能玉タイプ数: <@q>{total_types}</>
current_orbs=現在の本能玉:
orb_select=編集する本能玉を選択:
selected_orbs=選択中の本能玉:
edit_orbs_individually=各本能玉を個別に編集しますか (<@q>1</>)、それとも一括で編集しますか (<@q>2</>)?:
edit_orbs_all=選択したすべての本能玉を編集する値を入力してください (最大 <@t>{max}</>):
failed_to_load_orbs=本能玉を読み込めませんでした

edit_orbs_help=
>ヘルプ:
>利用可能な等級: {all_grades_str}
>利用可能なターゲット: {all_attributes_str}
>利用可能な効果/能力: {all_effects_str}
><@w>注意: すべての属性で、すべての等級や効果が利用できるとは限りません。</>
>入力例:
>    <c>aku</> - <c>悪魔</> 本能玉をすべて選択
>    <r>red</> <b>s</> - <b>s</> 等級の <r>赤い敵</> 本能玉をすべて選択
>    <b>alien</> <r>d</> <r>0</> - <r>ダメージ</> アップ <r>d</> 等級の <b>エイリアン</> 本能玉を選択
>    <o>c</> <dm>1</> - <o>c</> 等級のレジェンドストーリー強化本能玉を選択
><@q>すべて</> の本能玉を選択したい場合は、次のように入力してください:
>    <@q>*</>
><@q>複数選択</> したい場合は、次のように <@q>カンマ</> で区切ってください:
>    <b>s</> <bl>black</> <g>4</>,<r>d</> <o>3</>,<g>floating</>
>
