whole_chapters=章全体
individual_stages=個別ステージ
treasure_groups=お宝グループ / セット
treasure_dialog=<@t>章全体を一括</>、<@t>個別ステージ</>、または <@t>お宝グループ</> のどれのお宝を編集しますか?:
treasures_edited=<@su>お宝を編集しました</>
per_chapter=章ごと
all_selected_chapters=選択したすべての章
edit_per_chapter=<@t>選択したすべての章</> のデータを編集しますか、それとも <@t>各章を個別</> に編集しますか?:
no_treasure=お宝なし
custom_treasure_level=カスタムお宝レベル (<@w>何をしているか分かる場合のみ編集してください!</>)
treasure_level_dialog=設定したいお宝レベルを入力してください:
custom_treasure_level_dialog=設定したいカスタムお宝レベルを入力してください:
select_stage_by_id=ID でステージを選択
select_stage_by_name=名前でステージを選択
select_stage_dialog=ステージを <@t>ID</> と <@t>名前</> のどちらで選択しますか?:
select_stage_id=選択したいステージ ID を入力してください {{range_input}}
select_stages_name=ステージを選択:
select_treasure_groups=編集するお宝グループを選択してください:
story_treasures=ストーリーのお宝
current_chapter=現在の章: <@t>{chapter_name}</>
current_treasure_group=現在のお宝グループ: <@t>{treasure_group_name}</>
group_individual=個別グループ
group_all_at_once=選択したすべてのグループ
select_treasure_groups_individual=各 <@t>お宝グループ</> のお宝レベルを個別に編集しますか、それとも <@t>選択したすべてのグループ</> を一括で編集しますか?:
