claim=受け取り
unclaim=未受け取りに戻す
fix_claimed=受け取り状態を修正
claim_or_unclaim_ur=ユーザーランク報酬を <@t>受け取り済み</>、<@t>未受け取り</>、または <@t>受け取り状態を修正 (現在のユーザーランクを超える報酬を未受け取りに戻す)</> のどれにしますか?:
select_ur=ユーザーランク報酬を選択
ur_claimed_success=<@su>ユーザーランク報酬を受け取り済みにしました</>
ur_unclaimed_success=<@su>ユーザーランク報酬を未受け取りに戻しました</>
ur_string=ランク: <@s>{rank}</>: {description}
ur_fix_claimed_success=<@su>ユーザーランク報酬の受け取り状態を修正しました</>
