another_path=パスを手動入力
select_files_dir=ディレクトリ内のファイルを選択:
enter_path=ファイルパス/場所を入力してください:
enter_path_dir=フォルダパス/場所を入力してください:
enter_path_default=ファイルパス/場所を入力してください (既定: <@t>{default}</>):
current_files_dir=<@t>{dir}</> 内の現在のファイル:
other_dir=別のディレクトリを入力
no_files_dir=<@e>ディレクトリ内にファイルがありません</>
path_not_exists=<@e>パスが存在しません</>
