input_int=<@q>{min}</> から <@q>{max}</> までの数値を入力してください:
select_edit=<@t>{group_name}</> のオプションを選択してください:
input_int_default=<@q>{min}</> から <@q>{max}</> までの数値を入力してください (既定 <@q>{default}</>):
input_many=<@q>{min}</> から <@q>{max}</> までの数値をスペース区切りで入力してください:
input_single=<@q>{min}</> から <@q>{max}</> までの数値を入力してください:
input=<@t>{name}</> の値を入力してください (現在値: <@q>{value}</>) (最大値: <@q>{max}</>):
input_min=<@t>{name}</> の値を入力してください (現在値: <@q>{value}</>) (範囲: <@q>{min}</> - <@q>{max}</>):
input_non_max=<@t>{name}</> の値を入力してください (現在値: <@q>{value}</>):
input_all=すべての <@t>{name}</> の値を入力してください (最大値: <@q>{max}</>):
value_changed=<@su><@s>{name}</> を <@s>{value}</> に変更しました</>
value_gave=<@su><@s>{name}</> を付与しました</>
all_at_once=すべてのオプションを一括選択
invalid_input=<@e>入力が無効です。もう一度試してください。</>
invalid_input_int=<@e>入力が無効です。<@s>{min}</> から <@s>{max}</> までの数値を入力してください</>
select_option=オプションを選択:
finish=完了
features=機能:
go_back=戻る
yes_key=y
quit_key=q
range_input=スペース区切り (例 <@t>1 2 3 192</>)、範囲指定 (例 <@t>1-43</>)、または <@t>all</> を入力してください:
select_features=
>機能を選択するには、次のいずれかを入力してください
>- 左側の番号に対応する <@q>数字</>
>- 機能を検索するための <@t>テキスト</>
><@t>Enter</> を押すとすべての機能を表示できます
>一部の機能は <@t>カテゴリ</> です。選択すると、その <@t>サブ機能</> がすべて表示されます
>入力:

individual=個別
edit_all_at_once=一括
