# Full documentation: https://codeberg.org/fieryhenry/ExampleEditorLocale#format-of-the-properties-files
# color formatting
#
# <@p> = primary color
# <@s> = secondary color
# <@t> = tertiary color
# <@q> = quaternary color
# <@e> = error color
# <@w> = warning color
# <@su> = success color
#
# </> = close current color
# When coloring, use the above formatting tags, not the actual color codes / names so that different colors can be used for different themes.
# You should only use the actual color codes / names if the exact colors are important, such coloring a target red talent orb as red.
# If you want to write < or > or / in the text, escape them with a backslash (\) e.g. \< or \> or \/
#
# <#rrggbb> = hex color
#
# <w> = white
# <bl> = black
# <r> = red
# <g> = green
# <b> = blue
# <y> = yellow
# <m> = magenta
# <c> = cyan
# <dy> = dark yellow
# <dg> = dark grey
# <db> = dark blue
# <dc> = dark cyan
# <dm> = dark magenta
# <dr> = dark red
# <dgn> = dark green
# <lg> = light grey
# <o> = orange

downloading=<@s>{pack_name}</> から <@s>{file_name}</> をダウンロードしています (バージョン <@s>{version}</>, 国コード <@s>{country_code}</>)
failed_to_download_game_data=<@e><@s>{pack_name}</> から <@s>{file_name}</> のゲームデータをダウンロードできませんでした (バージョン <@s>{version}</>, 国コード <@s>{country_code}</>)。URL: <@s>{url}</s> インターネット接続を確認してください。</>
failed_to_get_game_versions=<@e>ゲームバージョンを取得できませんでした。インターネット接続を確認してください。</>
no_device_error=<@e>接続中のデバイスが見つかりません</>
no_package_name_error=<@e>にゃんこ大戦争のパッケージが見つかりません。端末が root 化されていないか、もう一度試す前に一度ネコ基地に入る必要があるかもしれません。</>
exit=終了
tkinter_not_found=<@e>tkinter が見つかりません。モバイル環境でない場合は、インストールしてから再試行してください。</>
tkinter_not_found_enter_path_file={initialfile} ファイルのパス/場所を入力してください:
tkinter_not_found_enter_path_file_save={initialfile} ファイルの保存先パス/場所を入力してください:
tkinter_not_found_enter_path_dir=代わりに {initialdir} フォルダのパス/場所を入力してください:
discord_url=https://discord.gg/DvmMgvn5ZB

welcome=
><@t><@s>Battle Cats Save File Editor</> へようこそ!
>作者: <@s>fieryhenry</>
>
>Codeberg: <@s>https://codeberg.org/fieryhenry/BCSFE-Python</>
>Discord: <@s>{{discord_url}}</> - バグ報告は <@s>#bug-reports</>、要望は <@s>#suggestions</> へ
>寄付: <@s>https://ko-fi.com/fieryhenry</>
>
>設定ファイルの場所: <@s>{config_path}</>
>
>{theme_text}
>
>{locale_text}
>
><@q>謝辞:
>- <@s>Lethal's editor</>: セーブデータのパッチ方法や cat food/xp 編集方法を調べるうえで着想と助けを得ました: <@s>https://www.reddit.com/r/BattleCatsCheats/comments/djehhn/editoren/</>
>- <@s>Beeven</> と <@s>csehydrogen</> のコード: セーブデータのパッチ方法を理解する助けになりました: https://github.com/beeven/battlecats and https://github.com/csehydrogen/BattleCatsHacker
>- この開発を支援し、継続する動機をくれたすべての人: <@s>https://ko-fi.com/fieryhenry</>
>- セーブ提供、バグ報告、新機能提案、そして素晴らしいコミュニティを作ってくれた Discord のみなさん: <@s>{{discord_url}}</></>
>
><@w>このプログラムにお金を払った場合、あなたはだまされています。このプログラムは無料かつオープンソースです。</>
>
><@w>このツールは自己責任で使用してください。BAN やセーブファイル破損などの損害について、作者は責任を負いません。
>セーブエディタ側でも問題が起きないよう対策はしていますが、セーブが安全であることは保証できません。
>もしセーブが破損した場合でも、Discord へ報告してください。
>編集前にセーブファイルのバックアップを作成することをおすすめします。</>

report_message=Discord の <@s>#bug-reports</> に報告してください: <@s>{{discord_url}}</>
report_message_l=discord の <@s>#bug-reports</> に報告してください: <@s>{{discord_url}}</>
try_again_message=もう一度試してください。エラーが続く場合は {{report_message_l}}
all=すべて

error=<@e>エラーが発生しました (<@s>{error}</>, エディタバージョン: <@s>{version}</>) {{report_message_l}}\n{traceback}
see_log=<@e>詳細はログファイルを確認してください。</>
max=最大
none=なし
unknown=不明

leave=\n<@q>Battle Cats Save File Editor をご利用いただきありがとうございました!</>
checking_for_changes=<@t>変更を確認しています...</>
no_changes=<@su>変更は見つかりませんでした。</>
changes_found=<@su>変更が見つかりました。</>

y/n=y/n
yes=yes

git_not_installed=<@e>Git がインストールされていません。Git をインストールし、PATH に追加してから再試行してください。</>
failed_to_get_repo=<@e>リポジトリを取得できませんでした: "<@t>{url}</>"。存在しないか、インターネット接続がない可能性があります</>
failed_to_run_git_cmd=<@e>git コマンドを実行できませんでした: "<@t>{cmd}</>"。インターネット接続を確認してください</>
cancel=キャンセル

update_external=外部コンテンツを更新
updating_external_content=<@q>外部コンテンツを更新しています...</>

downloading_map_names=<@q>ステージ名を取得しています... (コード: <@t>{code}</>)。時間がかかる場合があります...</>

select_device=デバイスを選択:

continue_q=続行しますか? ({{y/n}}):

no_data_version=<@e>利用可能な最新ゲームデータバージョンがありません。インターネット接続の問題の可能性があります。もう一度試してください。</>

no_feature_with_name=<@e>名前が <@s>{name}</> の機能は見つかりませんでした</>
