save_load_option=セーブファイルの読み込み方法を選択してください:
download_save=引継ぎコードと認証番号を使ってセーブファイルをダウンロード
select_save_file=ファイルからセーブファイルを選択
adb_pull_save=adb を使ってデバイスからセーブファイルを取得
load_save_data_json=JSON からセーブデータを読み込み
root_storage_pull_save=root ストレージからセーブファイルを取得
save_save_dialog=セーブファイルを保存
save_downloaded=<@su>セーブファイルを <@s>{path}</> にダウンロードしました</>
save_json_dialog=セーブデータを JSON に保存
load_from_documents=<@s>{path}</> からセーブファイルを読み込み
save_file_not_found=<@e>セーブファイルが見つかりません</>
save_file_found=<@su>セーブを読み込んでいます: <@t>{path}</></>

parse_save_error=<@e>セーブファイルの解析中にエラーが発生しました: {error}\n(エディタバージョン: <@s>{version}</>) (ゲームバージョン: <@s>{game_version}</>) (国コード: <@s>{country_code}</>)\n{{report_message}}</>
load_json_fail=<@e>JSON からセーブデータを読み込めませんでした ({error})</>
parse_json_fail=<@e>JSON ファイルを読み取れませんでした。本当に JSON 形式のファイルですか?</e>
editor_version_mismatch=<@w>エディタバージョンが一致しません。このセーブファイルはこのエディタと互換性がない可能性があります。JSON バージョン: <@t>{json_version}</>, エディタバージョン: <@t>{editor_version}</></>
save_management=セーブ管理
save_save=セーブを保存
save_save_file=指定したファイルへセーブを保存
save_save_documents={path} へセーブを保存
save_upload=セーブファイルをサーバーへアップロードし、引継ぎコードと認証番号を取得
unban_account=アカウントの BAN 解除 / 別端末使用中エラーを修正

adb_push_rerun=adb を使ってセーブファイルをデバイスへ送信 (送信後にゲームを再起動)
adb_push=adb を使ってセーブファイルをデバイスへ送信 (送信後にゲームを再起動しない)
adb_push_success=<@su>セーブファイルをデバイスへ送信しました</>
adb_push_fail=<@e>セーブファイルをデバイスへ送信できませんでした</> ({error})
adb_rerun_success=<@su>ゲームを再起動しました</>
adb_rerun_fail=<@e>ゲームを再起動できませんでした</> ({error})

export_save=セーブファイルを JSON にエクスポート
save_success=<@su>セーブファイルを <@s>{path}</> に保存しました</>
export_success=<@su>セーブデータを <@s>{path}</> にエクスポートしました</>
init_save=セーブファイルをリセット
init_save_confirm=本当にセーブファイルをリセットしますか? ({{y/n}}):
init_save_success=<@su>セーブファイルをリセットしました</>

adb_pulling=<@q>パッケージ名 <@s>{package_name}</> のセーブファイルを adb でデバイスから取得しています...</>
adb_pull_fail=<@e>パッケージ名 <@s>{package_name}</> のセーブファイルを adb でデバイスから取得できませんでした ({error})
storage_pulling=<@q>パッケージ名 <@s>{package_name}</> のセーブファイルを root ストレージから取得しています...</>
storage_pull_fail=<@e>パッケージ名 <@s>{package_name}</> のセーブファイルを root ストレージから取得できませんでした ({error})

not_rooted_error=<@e>デバイスが root 化されていないか、エディタが root 権限で実行されていないようです</>

upload_items=管理対象アイテムをサーバーへアップロード
upload_items_success=<@su>管理対象アイテムをアップロードしました</>
upload_items_fail=<@e>管理対象アイテムのアップロードに失敗しました</>

load_save=セーブファイルを読み込み
load_save_success=<@su>セーブファイルを読み込みました</>
account=アカウント

save_before_exit=<@q>終了前に最新の変更を保存しますか? (<@s>y</>/<@s>n</>):</>
save_temp_success=<@su>一時ファイルからセーブファイルを復元しました</>
save_temp_fail=<@e>一時ファイルからセーブファイルを復元できませんでした。最新のセーブ変更は失われました</> ({error})\n{traceback}
save_temp_not_found=<@e>一時ファイルからセーブファイルを復元できませんでした。最新のセーブ変更は失われました</> (一時ファイルが見つかりません)

cant_detect_cc=<@w>セーブファイルから国コードを検出できませんでした。\n国コードを手動で入力してください</>
failed_to_load_save_gv=セーブファイルは読み込まれましたが、一部の値が想定と異なっていました。セーブ破損を防ぐためエラーにしました
failed_to_load_save=セーブファイルを読み込めませんでした
failed_to_save_save=セーブファイルを保存できませんでした

game_version_dialog=ゲームバージョンを入力してください (例 <@t>12.2.1</>):
invalid_game_version=<@e>ゲームバージョンが無効です</>
country_code_set=<@su>国コードを <@s>{cc}</> に設定しました</>
game_version_set=<@su>ゲームバージョンを <@s>{version}</> に設定しました</>

convert_region=国コードを変換 (例 en -\> jp)
convert_version=ゲームバージョンを変換 (例 12.2.1 -\> 12.2.0)

cc_warning=<@w>警告: セーブファイルに問題が起きる可能性があります。バグやクラッシュが発生することがあります。バグ報告時は、この機能を使用したことを必ず伝えてください。この機能の実行後、ゲーム側で必要な変更がセーブファイルへ反映されるよう、ネコ基地/パワーアップ画面に入ってください。</>\n現在の国コード: <@t>{current}</>
gv_warning=<@w>警告: セーブファイルに問題が起きる可能性があります。バグやクラッシュが発生することがあります。バグ報告時は、この機能を使用したことを必ず伝えてください。この機能の実行後、ゲーム側で必要な変更がセーブファイルへ反映されるよう、ネコ基地/パワーアップ画面に入ってください。</>\n現在のゲームバージョン: <@t>{current}</>

create_new_save_success=<@su>新しいセーブファイルを作成しました</>
create_new_save=新しいセーブファイルを作成
create_new_save_warning=<@w>警告: 自動作成されたセーブファイルでは、多くのエディタ機能が動作しません。まずゲームで読み込み、その後エディタで再読み込みする必要があります\nこの仕様は今後のエディタバージョンで変更される可能性があります。</>

parse_ignored_error=<@w>警告: <@e>{error}<>\n<@w><@s>Ignore Parse Error</> 設定が有効なため無視します。問題が起きる可能性があります!</> 

select_package_name=パッケージ名を選択:

adb_not_installed=
><@e>adb が PATH 環境変数に追加されていないか、実行ファイルのパスが正しくありません。設定から adb パスを編集してみてください
>現在値: <@s>{path}</>
>エラー: <@s>{error}</></>

waydroid_not_installed=<@e>Waydroid がインストールされていないか、エラーが発生しました: {error}</>

root_push_not_android_error=<@e>root push は Android デバイスでのみ利用できます</>
root_push_success=<@su>root ストレージへセーブを書き込みました</>
root_push_fail=<@e>root ストレージへセーブを書き込めませんでした。エラー: <@s>{error}</></>

root_rerun_success=<@su>ゲームを再起動しました</>
root_rerun_fail=<@e>ゲームを再起動できませんでした。エラー: <@s>{error}</></>

root_push=root を使ってセーブを直接ゲームへ送信
root_push_rerun=root を使ってセーブを直接ゲームへ送信 (その後ゲームを再起動)

select_recent=最近のセーブを選択:
recent_save=<@s><@q>{inquiry_code}</> <@t>{cc}</>-<@t>{gv}</> @ <@t>{year}</>-<@t>{month}</>-<@t>{day}</> <@t>{hour}</>:<@t>{minute}</>:<@t>{second}</> - 元のパス: <@q>{name}</></>

load_recent_saves=最近のセーブとバックアップから読み込み
no_recent_saves=<@w>最近のセーブはありません</>
current_save=\n現在のセーブ: <@t>{cc}</>-<@t>{gv}</> 問い合わせコード: <@t>{inquiry_code}</>
