transfer_code=引継ぎコード
enter_transfer_code=引継ぎコードを入力してください:
confirmation_code=認証番号
enter_confirmation_code=認証番号を入力してください:
country_code=国コード
country_code_select=国コードを選択:
invalid_codes_error=<@e>セーブファイルのダウンロードに失敗しました。引継ぎコード、認証番号、国コードを確認してから再試行してください。</>
display_response_debug_info_q=レスポンスのデバッグ情報を表示しますか? ({{y/n}}):
response_text_display=
>URL: <@q>{url}</>
>リクエストヘッダー: <@q>{request_headers}</>
>リクエスト本文: <@q>{request_body}</>
>
>レスポンスヘッダー: <@q>{response_headers}</>
>レスポンス本文: <@q>{response_body}</>

downloading_save_file=サーバーからセーブファイルをダウンロードしています (引継ぎコード: <@q>{transfer_code}</>, 認証番号: <@q>{confirmation_code}</>, 国コード: <@q>{country_code}</>)...
upload_result=
><@su>
>引継ぎコード: <@s>{transfer_code}</>
>認証番号: <@s>{confirmation_code}</>
></>

upload_fail=<@e>セーブファイルのアップロードに失敗しました。{{try_again_message}} {{see_log}}</>
unban_fail=<@e>アカウントの BAN 解除に失敗しました。{{try_again_message}} {{see_log}}</>
unban_success=<@su>アカウントの BAN 解除に成功しました。</>
upload_items_checker_confirm=現在のセーブファイルで、まだ追跡されていない管理対象アイテムがあります。今アップロードしますか? ({{y/n}}):
strict_ban_prevention_enabled=<@w>厳密な BAN 防止が有効です。セーブファイル/管理対象アイテムをアップロードする前に新しいアカウントを作成します。</>
create_new_account_success=<@su>アカウントを作成しました。</>
create_new_account_fail=<@e>アカウントを作成できませんでした。{{try_again_message}} {{see_log}}</>

uploading_save_file=<@q>セーブファイルをサーバーへアップロードしています...</>
getting_codes=<@q>引継ぎコードと認証番号を取得しています...</>
getting_auth_token=<@q>アカウント認証トークンを取得しています...</>
refreshing_password=<@q>アカウントパスワードを更新しています...</>
getting_password=<@q>アカウントパスワードを取得しています...</>
getting_save_key=<@q>アカウントのセーブキーを取得しています...</>

inquiry_code_warning=<@w>警告: 問い合わせコードを編集すると、アカウントが使用不能になる可能性があります。自己責任で使用してください。</>\n{{do_you_want_to_continue}}
password_refresh_token_warning=<@w>警告: パスワード更新トークンを編集すると、アカウントが使用不能になる可能性があります。自己責任で使用してください。</>\n{{do_you_want_to_continue}}

no_internet=<@e>インターネット接続がありません。接続を確認してから再試行してください。</>

transfer_backup=<@su>引継ぎ用セーブファイルのバックアップを <@t>{path}</> に保存しました</>
transfer_backup_fail=<@e>{error} により、引継ぎ用バックアップファイルを <@t>{path}</> に保存できませんでした</>

retry_auth_token=<@e>認証トークンを取得できませんでした。再試行しています...</>

downloading_compressed_data=<@su><@s>{url}</> からゲームデータをダウンロードしています</>
clear_game_data_q=ダウンロード済みのゲームデータをすべて削除しますか? ({{y/n}}):
cleared_game_data=<@su>ゲームデータを削除しました</>

validating_game_repo=ゲームデータリポジトリを検証しています...
invalid_response=<@e>レスポンスコードが無効です: <@s>{response_code}</>。期待値: <@s>200</></>
no_internet_or_connection_error=<@e>ゲームデータリポジトリへ接続できませんでした</>
invalid_url=<@e>URL が無効です</>

use_alternative_repo=<@e>ゲームデータリポジトリの取得に失敗しました。インターネット接続の問題か、ネットワーク上でリポジトリがブロックされている可能性があります。</> 代替のゲームデータリポジトリとして <@t>{repo}</t> に切り替えますか? ({{y/n}}):
