theme_text=
>現在のテーマ: <@s>{theme_name}</> (バージョン <@s>{theme_version}</>)
>作成者: <@s>{theme_author}</>
>テーマファイルの場所: <@s>{theme_path}</>

default_theme_text=
>現在のテーマ: <@s>Default</>
>テーマファイルの場所: <@s>{theme_path}</>

checking_for_theme_updates=外部テーマ <@t>{theme_name}</> の更新を確認しています...
external_theme_updated=<@su>外部テーマ <@t>{theme_name}</> をバージョン <@t>{version}<@t> に更新しました。\n{{restart_to_see_changes}}</>
external_theme_no_update=<@su>外部テーマ <@t>{theme_name}</> は更新不要です。最新バージョンは <@t>{version}<@t> です</>
theme_changed=<@su>テーマを <@t>{theme_name}</> に変更しました。\n{{restart_to_see_changes}}</>
theme_removed=<@su>テーマ <@t>{theme_name}</> を削除しました。\n{{restart_to_see_changes}}</>
no_external_themes=<@w>外部テーマが見つかりません</>


theme_dialog=テーマを選択してください:
add_theme=テーマを追加
remove_theme=テーマを削除
theme_remove_dialog=削除するテーマを選択してください:
enter_theme_git_repo=テーマの git リポジトリを入力してください (例 <@t>https://codeberg.org/fieryhenry/ExampleEditorTheme.git</>):
theme_already_exists=<@e><@s>{theme_name}</> という名前のテーマはすでに存在します。</>\n上書きしますか? ({{y/n}}):
theme_added=<@su>テーマを追加しました</>
