local_version=<@q>ローカルバージョン: <@s>{local_version}</></>
latest_version=<@q>最新バージョン: <@s>{latest_version}</></>

update_check_fail=<@e>更新確認に失敗しました。インターネット接続を確認してください。</>

update_available=
><@q>更新があります: <@s>{latest_version}</>
>更新しますか? <@t>({{y/n}})</>:
update_success=
><@t>更新が完了しました
>アプリケーションを再起動してください</>
update_fail=
><@e>更新に失敗しました
>手動で更新してください</>
>コマンド: <@s>pip install --upgrade bcsfe</>

version_line={{local_version}} | {{latest_version}}

disable_update_message=更新メッセージを無効にしますか? <@t>({{y/n}}):</>
